version: '2'
# to run this on ci run:
# docker-compose -p ci down -v --remove-orphans
# docker-compose -f docker-compose.yml -f docker-compose.test.yml -p ci build
# docker-compose -f docker-compose.yml -f docker-compose.test.yml -p ci up -d

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
      - '29094:29094'
    environment:
      # For more details see See https://rmoff.net/2018/08/02/kafka-listeners-explained/
      - KAFKA_LISTENERS=LISTENER_INSIDE://kafka:29092,LISTENER_OUTSIDE://kafka:9092,LISTENER_ALICE://kafka:29094
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_INSIDE://kafka:29092,LISTENER_OUTSIDE://127.0.0.1:9092,LISTENER_ALICE://never-gonna-give-you-up:29094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INSIDE:PLAINTEXT,LISTENER_OUTSIDE:PLAINTEXT,LISTENER_ALICE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INSIDE
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper